// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: logservice/logservicepb/logservice.proto

package logservicepb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	heartbeatpb "github.com/pingcap/ticdc/heartbeatpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SubscriptionState struct {
	SubID        uint64                 `protobuf:"varint,1,opt,name=SubID,proto3" json:"SubID,omitempty"`
	Span         *heartbeatpb.TableSpan `protobuf:"bytes,2,opt,name=span,proto3" json:"span,omitempty"`
	CheckpointTs uint64                 `protobuf:"varint,3,opt,name=CheckpointTs,proto3" json:"CheckpointTs,omitempty"`
	ResolvedTs   uint64                 `protobuf:"varint,4,opt,name=ResolvedTs,proto3" json:"ResolvedTs,omitempty"`
}

func (m *SubscriptionState) Reset()         { *m = SubscriptionState{} }
func (m *SubscriptionState) String() string { return proto.CompactTextString(m) }
func (*SubscriptionState) ProtoMessage()    {}
func (*SubscriptionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1db670929506a40, []int{0}
}
func (m *SubscriptionState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubscriptionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubscriptionState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubscriptionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionState.Merge(m, src)
}
func (m *SubscriptionState) XXX_Size() int {
	return m.Size()
}
func (m *SubscriptionState) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionState.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionState proto.InternalMessageInfo

func (m *SubscriptionState) GetSubID() uint64 {
	if m != nil {
		return m.SubID
	}
	return 0
}

func (m *SubscriptionState) GetSpan() *heartbeatpb.TableSpan {
	if m != nil {
		return m.Span
	}
	return nil
}

func (m *SubscriptionState) GetCheckpointTs() uint64 {
	if m != nil {
		return m.CheckpointTs
	}
	return 0
}

func (m *SubscriptionState) GetResolvedTs() uint64 {
	if m != nil {
		return m.ResolvedTs
	}
	return 0
}

type SubscriptionStates struct {
	Subscriptions []*SubscriptionState `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
}

func (m *SubscriptionStates) Reset()         { *m = SubscriptionStates{} }
func (m *SubscriptionStates) String() string { return proto.CompactTextString(m) }
func (*SubscriptionStates) ProtoMessage()    {}
func (*SubscriptionStates) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1db670929506a40, []int{1}
}
func (m *SubscriptionStates) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubscriptionStates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubscriptionStates.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubscriptionStates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscriptionStates.Merge(m, src)
}
func (m *SubscriptionStates) XXX_Size() int {
	return m.Size()
}
func (m *SubscriptionStates) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscriptionStates.DiscardUnknown(m)
}

var xxx_messageInfo_SubscriptionStates proto.InternalMessageInfo

func (m *SubscriptionStates) GetSubscriptions() []*SubscriptionState {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type EventStoreState struct {
	Subscriptions map[int64]*SubscriptionStates `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *EventStoreState) Reset()         { *m = EventStoreState{} }
func (m *EventStoreState) String() string { return proto.CompactTextString(m) }
func (*EventStoreState) ProtoMessage()    {}
func (*EventStoreState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1db670929506a40, []int{2}
}
func (m *EventStoreState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventStoreState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventStoreState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventStoreState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStoreState.Merge(m, src)
}
func (m *EventStoreState) XXX_Size() int {
	return m.Size()
}
func (m *EventStoreState) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStoreState.DiscardUnknown(m)
}

var xxx_messageInfo_EventStoreState proto.InternalMessageInfo

func (m *EventStoreState) GetSubscriptions() map[int64]*SubscriptionStates {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

func init() {
	proto.RegisterType((*SubscriptionState)(nil), "logservicepb.SubscriptionState")
	proto.RegisterType((*SubscriptionStates)(nil), "logservicepb.SubscriptionStates")
	proto.RegisterType((*EventStoreState)(nil), "logservicepb.EventStoreState")
	proto.RegisterMapType((map[int64]*SubscriptionStates)(nil), "logservicepb.EventStoreState.SubscriptionsEntry")
}

func init() {
	proto.RegisterFile("logservice/logservicepb/logservice.proto", fileDescriptor_a1db670929506a40)
}

var fileDescriptor_a1db670929506a40 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0xed, 0x34, 0xed, 0x5b, 0x4c, 0xfb, 0x78, 0xcf, 0x41, 0x24, 0x54, 0x18, 0x43, 0x40, 0x08,
	0x2e, 0x12, 0xa9, 0x20, 0xe2, 0x46, 0x50, 0xbb, 0x70, 0x9b, 0x14, 0x17, 0xba, 0x9a, 0x99, 0x0e,
	0xed, 0xd0, 0x38, 0x33, 0x64, 0x26, 0x81, 0xfe, 0x85, 0x5b, 0xff, 0xc8, 0x8d, 0xd0, 0xa5, 0x4b,
	0x69, 0x7f, 0x44, 0x4c, 0x44, 0x93, 0x56, 0x70, 0x77, 0xef, 0x99, 0x73, 0xce, 0x9d, 0x73, 0xb9,
	0x30, 0x48, 0xd5, 0xd4, 0xf0, 0xac, 0x10, 0x8c, 0x47, 0xdf, 0xa5, 0xa6, 0xb5, 0x26, 0xd4, 0x99,
	0xb2, 0x0a, 0xf5, 0xeb, 0xcf, 0x83, 0xfd, 0x19, 0x27, 0x99, 0xa5, 0x9c, 0x58, 0x4d, 0xa3, 0xaf,
	0xba, 0xa2, 0xfa, 0x4f, 0x00, 0xee, 0x24, 0x39, 0x35, 0x2c, 0x13, 0xda, 0x0a, 0x25, 0x13, 0x4b,
	0x2c, 0x47, 0xbb, 0xb0, 0x9b, 0xe4, 0xf4, 0xe6, 0xda, 0x05, 0x1e, 0x08, 0x3a, 0x71, 0xd5, 0xa0,
	0x23, 0xd8, 0x31, 0x9a, 0x48, 0xb7, 0xed, 0x81, 0xa0, 0x37, 0xdc, 0x0b, 0x6b, 0xbe, 0xe1, 0x98,
	0xd0, 0x94, 0x27, 0x9a, 0xc8, 0xb8, 0xe4, 0x20, 0x1f, 0xf6, 0xaf, 0x66, 0x9c, 0xcd, 0xb5, 0x12,
	0xd2, 0x8e, 0x8d, 0xeb, 0x94, 0x46, 0x0d, 0x0c, 0x61, 0x08, 0x63, 0x6e, 0x54, 0x5a, 0xf0, 0xc9,
	0xd8, 0xb8, 0x9d, 0x92, 0x51, 0x43, 0xfc, 0x7b, 0x88, 0xb6, 0xbe, 0x66, 0xd0, 0x08, 0xfe, 0x35,
	0x35, 0xd4, 0xb8, 0xc0, 0x73, 0x82, 0xde, 0xf0, 0x20, 0xac, 0x87, 0x0e, 0xb7, 0x84, 0x71, 0x53,
	0xe5, 0xbf, 0x00, 0xf8, 0x6f, 0x54, 0x70, 0x69, 0x13, 0xab, 0x32, 0x5e, 0xc5, 0xbe, 0xfd, 0xd9,
	0xfa, 0xb8, 0x69, 0xbd, 0xa1, 0x6a, 0x8c, 0x32, 0x23, 0x69, 0xb3, 0xc5, 0xc6, 0xac, 0x01, 0x6d,
	0x06, 0xa9, 0x48, 0xe8, 0x3f, 0x74, 0xe6, 0x7c, 0x51, 0xae, 0xd8, 0x89, 0x3f, 0x4a, 0x74, 0x0a,
	0xbb, 0x05, 0x49, 0x73, 0xfe, 0xb9, 0x61, 0xef, 0x97, 0x48, 0x26, 0xae, 0xe8, 0xe7, 0xed, 0x33,
	0x70, 0x79, 0xf1, 0xbc, 0xc2, 0x60, 0xb9, 0xc2, 0xe0, 0x6d, 0x85, 0xc1, 0xe3, 0x1a, 0xb7, 0x96,
	0x6b, 0xdc, 0x7a, 0x5d, 0xe3, 0xd6, 0xdd, 0xe1, 0x54, 0xd8, 0x59, 0x4e, 0x43, 0xa6, 0x1e, 0x22,
	0x2d, 0xe4, 0x94, 0x11, 0x1d, 0x59, 0xc1, 0x26, 0xac, 0x71, 0x45, 0xf4, 0x4f, 0x79, 0x10, 0x27,
	0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x82, 0x2e, 0xc5, 0x14, 0x67, 0x02, 0x00, 0x00,
}

func (m *SubscriptionState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubscriptionState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubscriptionState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResolvedTs != 0 {
		i = encodeVarintLogservice(dAtA, i, uint64(m.ResolvedTs))
		i--
		dAtA[i] = 0x20
	}
	if m.CheckpointTs != 0 {
		i = encodeVarintLogservice(dAtA, i, uint64(m.CheckpointTs))
		i--
		dAtA[i] = 0x18
	}
	if m.Span != nil {
		{
			size, err := m.Span.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLogservice(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.SubID != 0 {
		i = encodeVarintLogservice(dAtA, i, uint64(m.SubID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SubscriptionStates) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubscriptionStates) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubscriptionStates) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Subscriptions) > 0 {
		for iNdEx := len(m.Subscriptions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Subscriptions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLogservice(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *EventStoreState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventStoreState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventStoreState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Subscriptions) > 0 {
		for k := range m.Subscriptions {
			v := m.Subscriptions[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintLogservice(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i = encodeVarintLogservice(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintLogservice(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintLogservice(dAtA []byte, offset int, v uint64) int {
	offset -= sovLogservice(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SubscriptionState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubID != 0 {
		n += 1 + sovLogservice(uint64(m.SubID))
	}
	if m.Span != nil {
		l = m.Span.Size()
		n += 1 + l + sovLogservice(uint64(l))
	}
	if m.CheckpointTs != 0 {
		n += 1 + sovLogservice(uint64(m.CheckpointTs))
	}
	if m.ResolvedTs != 0 {
		n += 1 + sovLogservice(uint64(m.ResolvedTs))
	}
	return n
}

func (m *SubscriptionStates) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Subscriptions) > 0 {
		for _, e := range m.Subscriptions {
			l = e.Size()
			n += 1 + l + sovLogservice(uint64(l))
		}
	}
	return n
}

func (m *EventStoreState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Subscriptions) > 0 {
		for k, v := range m.Subscriptions {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovLogservice(uint64(l))
			}
			mapEntrySize := 1 + sovLogservice(uint64(k)) + l
			n += mapEntrySize + 1 + sovLogservice(uint64(mapEntrySize))
		}
	}
	return n
}

func sovLogservice(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLogservice(x uint64) (n int) {
	return sovLogservice(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SubscriptionState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLogservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubscriptionState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubscriptionState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubID", wireType)
			}
			m.SubID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Span", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLogservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLogservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Span == nil {
				m.Span = &heartbeatpb.TableSpan{}
			}
			if err := m.Span.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CheckpointTs", wireType)
			}
			m.CheckpointTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CheckpointTs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolvedTs", wireType)
			}
			m.ResolvedTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolvedTs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLogservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLogservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubscriptionStates) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLogservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubscriptionStates: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubscriptionStates: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subscriptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLogservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLogservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subscriptions = append(m.Subscriptions, &SubscriptionState{})
			if err := m.Subscriptions[len(m.Subscriptions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLogservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLogservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventStoreState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLogservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventStoreState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventStoreState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subscriptions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLogservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLogservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLogservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Subscriptions == nil {
				m.Subscriptions = make(map[int64]*SubscriptionStates)
			}
			var mapkey int64
			var mapvalue *SubscriptionStates
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLogservice
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLogservice
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLogservice
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthLogservice
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthLogservice
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &SubscriptionStates{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipLogservice(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthLogservice
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Subscriptions[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLogservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLogservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLogservice(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLogservice
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLogservice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLogservice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLogservice
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLogservice
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLogservice
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLogservice        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLogservice          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLogservice = fmt.Errorf("proto: unexpected end of group")
)
