// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eventpb/event.proto

package eventpb

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	heartbeatpb "github.com/pingcap/ticdc/heartbeatpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OpType int32

const (
	OpType_OpTypePut    OpType = 0
	OpType_OpTypeDelete OpType = 1
)

var OpType_name = map[int32]string{
	0: "OpTypePut",
	1: "OpTypeDelete",
}

var OpType_value = map[string]int32{
	"OpTypePut":    0,
	"OpTypeDelete": 1,
}

func (x OpType) String() string {
	return proto.EnumName(OpType_name, int32(x))
}

func (OpType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d7fb2554dfcf7f7d, []int{0}
}

type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_ACTION_TYPE_REGISTER    ActionType = 1
	ActionType_ACTION_TYPE_REMOVE      ActionType = 2
	ActionType_ACTION_TYPE_PAUSE       ActionType = 3
	ActionType_ACTION_TYPE_RESUME      ActionType = 4
	ActionType_ACTION_TYPE_RESET       ActionType = 5
)

var ActionType_name = map[int32]string{
	0: "ACTION_TYPE_UNSPECIFIED",
	1: "ACTION_TYPE_REGISTER",
	2: "ACTION_TYPE_REMOVE",
	3: "ACTION_TYPE_PAUSE",
	4: "ACTION_TYPE_RESUME",
	5: "ACTION_TYPE_RESET",
}

var ActionType_value = map[string]int32{
	"ACTION_TYPE_UNSPECIFIED": 0,
	"ACTION_TYPE_REGISTER":    1,
	"ACTION_TYPE_REMOVE":      2,
	"ACTION_TYPE_PAUSE":       3,
	"ACTION_TYPE_RESUME":      4,
	"ACTION_TYPE_RESET":       5,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d7fb2554dfcf7f7d, []int{1}
}

type EventFilterRule struct {
	Matcher                  []string `protobuf:"bytes,1,rep,name=matcher,proto3" json:"matcher,omitempty"`
	IgnoreEvent              []string `protobuf:"bytes,2,rep,name=ignore_event,json=ignoreEvent,proto3" json:"ignore_event,omitempty"`
	IgnoreSql                []string `protobuf:"bytes,3,rep,name=ignore_sql,json=ignoreSql,proto3" json:"ignore_sql,omitempty"`
	IgnoreInsertValueExpr    string   `protobuf:"bytes,4,opt,name=ignore_insert_value_expr,json=ignoreInsertValueExpr,proto3" json:"ignore_insert_value_expr,omitempty"`
	IgnoreUpdateNewValueExpr string   `protobuf:"bytes,5,opt,name=ignore_update_new_value_expr,json=ignoreUpdateNewValueExpr,proto3" json:"ignore_update_new_value_expr,omitempty"`
	IgnoreUpdateOldValueExpr string   `protobuf:"bytes,6,opt,name=ignore_update_old_value_expr,json=ignoreUpdateOldValueExpr,proto3" json:"ignore_update_old_value_expr,omitempty"`
	IgnoreDeleteValueExpr    string   `protobuf:"bytes,7,opt,name=ignore_delete_value_expr,json=ignoreDeleteValueExpr,proto3" json:"ignore_delete_value_expr,omitempty"`
}

func (m *EventFilterRule) Reset()         { *m = EventFilterRule{} }
func (m *EventFilterRule) String() string { return proto.CompactTextString(m) }
func (*EventFilterRule) ProtoMessage()    {}
func (*EventFilterRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7fb2554dfcf7f7d, []int{0}
}
func (m *EventFilterRule) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventFilterRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventFilterRule.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventFilterRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventFilterRule.Merge(m, src)
}
func (m *EventFilterRule) XXX_Size() int {
	return m.Size()
}
func (m *EventFilterRule) XXX_DiscardUnknown() {
	xxx_messageInfo_EventFilterRule.DiscardUnknown(m)
}

var xxx_messageInfo_EventFilterRule proto.InternalMessageInfo

func (m *EventFilterRule) GetMatcher() []string {
	if m != nil {
		return m.Matcher
	}
	return nil
}

func (m *EventFilterRule) GetIgnoreEvent() []string {
	if m != nil {
		return m.IgnoreEvent
	}
	return nil
}

func (m *EventFilterRule) GetIgnoreSql() []string {
	if m != nil {
		return m.IgnoreSql
	}
	return nil
}

func (m *EventFilterRule) GetIgnoreInsertValueExpr() string {
	if m != nil {
		return m.IgnoreInsertValueExpr
	}
	return ""
}

func (m *EventFilterRule) GetIgnoreUpdateNewValueExpr() string {
	if m != nil {
		return m.IgnoreUpdateNewValueExpr
	}
	return ""
}

func (m *EventFilterRule) GetIgnoreUpdateOldValueExpr() string {
	if m != nil {
		return m.IgnoreUpdateOldValueExpr
	}
	return ""
}

func (m *EventFilterRule) GetIgnoreDeleteValueExpr() string {
	if m != nil {
		return m.IgnoreDeleteValueExpr
	}
	return ""
}

type FilterConfig struct {
	Rules            []string           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	IgnoreTxnStartTs []uint64           `protobuf:"varint,2,rep,packed,name=ignore_txn_start_ts,json=ignoreTxnStartTs,proto3" json:"ignore_txn_start_ts,omitempty"`
	EventFilters     []*EventFilterRule `protobuf:"bytes,3,rep,name=EventFilters,proto3" json:"EventFilters,omitempty"`
}

func (m *FilterConfig) Reset()         { *m = FilterConfig{} }
func (m *FilterConfig) String() string { return proto.CompactTextString(m) }
func (*FilterConfig) ProtoMessage()    {}
func (*FilterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7fb2554dfcf7f7d, []int{1}
}
func (m *FilterConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FilterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FilterConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FilterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterConfig.Merge(m, src)
}
func (m *FilterConfig) XXX_Size() int {
	return m.Size()
}
func (m *FilterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FilterConfig proto.InternalMessageInfo

func (m *FilterConfig) GetRules() []string {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *FilterConfig) GetIgnoreTxnStartTs() []uint64 {
	if m != nil {
		return m.IgnoreTxnStartTs
	}
	return nil
}

func (m *FilterConfig) GetEventFilters() []*EventFilterRule {
	if m != nil {
		return m.EventFilters
	}
	return nil
}

type ResolvedTs struct {
}

func (m *ResolvedTs) Reset()         { *m = ResolvedTs{} }
func (m *ResolvedTs) String() string { return proto.CompactTextString(m) }
func (*ResolvedTs) ProtoMessage()    {}
func (*ResolvedTs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7fb2554dfcf7f7d, []int{2}
}
func (m *ResolvedTs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResolvedTs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResolvedTs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResolvedTs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedTs.Merge(m, src)
}
func (m *ResolvedTs) XXX_Size() int {
	return m.Size()
}
func (m *ResolvedTs) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedTs.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedTs proto.InternalMessageInfo

type Event struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// nil for delete type
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// nil for insert type
	OldValue []byte `protobuf:"bytes,3,opt,name=OldValue,proto3" json:"OldValue,omitempty"`
	OpType   OpType `protobuf:"varint,4,opt,name=op_type,json=opType,proto3,enum=eventpb.OpType" json:"op_type,omitempty"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7fb2554dfcf7f7d, []int{3}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Event.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return m.Size()
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Event) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Event) GetOldValue() []byte {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *Event) GetOpType() OpType {
	if m != nil {
		return m.OpType
	}
	return OpType_OpTypePut
}

type TxnEvent struct {
	Events   []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	CommitTs uint64   `protobuf:"varint,2,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	StartTs  uint64   `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
}

func (m *TxnEvent) Reset()         { *m = TxnEvent{} }
func (m *TxnEvent) String() string { return proto.CompactTextString(m) }
func (*TxnEvent) ProtoMessage()    {}
func (*TxnEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7fb2554dfcf7f7d, []int{4}
}
func (m *TxnEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxnEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxnEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxnEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxnEvent.Merge(m, src)
}
func (m *TxnEvent) XXX_Size() int {
	return m.Size()
}
func (m *TxnEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TxnEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TxnEvent proto.InternalMessageInfo

func (m *TxnEvent) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *TxnEvent) GetCommitTs() uint64 {
	if m != nil {
		return m.CommitTs
	}
	return 0
}

func (m *TxnEvent) GetStartTs() uint64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

type TableInfo struct {
}

func (m *TableInfo) Reset()         { *m = TableInfo{} }
func (m *TableInfo) String() string { return proto.CompactTextString(m) }
func (*TableInfo) ProtoMessage()    {}
func (*TableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7fb2554dfcf7f7d, []int{5}
}
func (m *TableInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TableInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableInfo.Merge(m, src)
}
func (m *TableInfo) XXX_Size() int {
	return m.Size()
}
func (m *TableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TableInfo proto.InternalMessageInfo

type EventFeed struct {
	TxnEvents    []*TxnEvent               `protobuf:"bytes,1,rep,name=txn_events,json=txnEvents,proto3" json:"txn_events,omitempty"`
	ResolvedTs   uint64                    `protobuf:"varint,2,opt,name=resolved_ts,json=resolvedTs,proto3" json:"resolved_ts,omitempty"`
	DispatcherId *heartbeatpb.DispatcherID `protobuf:"bytes,3,opt,name=dispatcher_id,json=dispatcherId,proto3" json:"dispatcher_id,omitempty"`
	Ratio        float32                   `protobuf:"fixed32,4,opt,name=ratio,proto3" json:"ratio,omitempty"`
	TableInfo    *TableInfo                `protobuf:"bytes,5,opt,name=table_info,json=tableInfo,proto3" json:"table_info,omitempty"`
}

func (m *EventFeed) Reset()         { *m = EventFeed{} }
func (m *EventFeed) String() string { return proto.CompactTextString(m) }
func (*EventFeed) ProtoMessage()    {}
func (*EventFeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7fb2554dfcf7f7d, []int{6}
}
func (m *EventFeed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventFeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventFeed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventFeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventFeed.Merge(m, src)
}
func (m *EventFeed) XXX_Size() int {
	return m.Size()
}
func (m *EventFeed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventFeed.DiscardUnknown(m)
}

var xxx_messageInfo_EventFeed proto.InternalMessageInfo

func (m *EventFeed) GetTxnEvents() []*TxnEvent {
	if m != nil {
		return m.TxnEvents
	}
	return nil
}

func (m *EventFeed) GetResolvedTs() uint64 {
	if m != nil {
		return m.ResolvedTs
	}
	return 0
}

func (m *EventFeed) GetDispatcherId() *heartbeatpb.DispatcherID {
	if m != nil {
		return m.DispatcherId
	}
	return nil
}

func (m *EventFeed) GetRatio() float32 {
	if m != nil {
		return m.Ratio
	}
	return 0
}

func (m *EventFeed) GetTableInfo() *TableInfo {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

type RegisterDispatcherRequest struct {
	ChangefeedId      *heartbeatpb.ChangefeedID `protobuf:"bytes,1,opt,name=changefeed_id,json=changefeedId,proto3" json:"changefeed_id,omitempty"`
	DispatcherId      *heartbeatpb.DispatcherID `protobuf:"bytes,2,opt,name=dispatcher_id,json=dispatcherId,proto3" json:"dispatcher_id,omitempty"`
	TableSpan         *heartbeatpb.TableSpan    `protobuf:"bytes,3,opt,name=table_span,json=tableSpan,proto3" json:"table_span,omitempty"`
	StartTs           uint64                    `protobuf:"varint,4,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	ServerId          string                    `protobuf:"bytes,5,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ActionType        ActionType                `protobuf:"varint,6,opt,name=action_type,json=actionType,proto3,enum=eventpb.ActionType" json:"action_type,omitempty"`
	FilterConfig      *FilterConfig             `protobuf:"bytes,7,opt,name=filter_config,json=filterConfig,proto3" json:"filter_config,omitempty"`
	EnableSyncPoint   bool                      `protobuf:"varint,8,opt,name=enable_sync_point,json=enableSyncPoint,proto3" json:"enable_sync_point,omitempty"`
	SyncPointTs       uint64                    `protobuf:"varint,9,opt,name=sync_point_ts,json=syncPointTs,proto3" json:"sync_point_ts,omitempty"`
	SyncPointInterval uint64                    `protobuf:"varint,10,opt,name=sync_point_interval,json=syncPointInterval,proto3" json:"sync_point_interval,omitempty"`
	OnlyReuse         bool                      `protobuf:"varint,11,opt,name=only_reuse,json=onlyReuse,proto3" json:"only_reuse,omitempty"`
}

func (m *RegisterDispatcherRequest) Reset()         { *m = RegisterDispatcherRequest{} }
func (m *RegisterDispatcherRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterDispatcherRequest) ProtoMessage()    {}
func (*RegisterDispatcherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7fb2554dfcf7f7d, []int{7}
}
func (m *RegisterDispatcherRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterDispatcherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterDispatcherRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterDispatcherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDispatcherRequest.Merge(m, src)
}
func (m *RegisterDispatcherRequest) XXX_Size() int {
	return m.Size()
}
func (m *RegisterDispatcherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDispatcherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDispatcherRequest proto.InternalMessageInfo

func (m *RegisterDispatcherRequest) GetChangefeedId() *heartbeatpb.ChangefeedID {
	if m != nil {
		return m.ChangefeedId
	}
	return nil
}

func (m *RegisterDispatcherRequest) GetDispatcherId() *heartbeatpb.DispatcherID {
	if m != nil {
		return m.DispatcherId
	}
	return nil
}

func (m *RegisterDispatcherRequest) GetTableSpan() *heartbeatpb.TableSpan {
	if m != nil {
		return m.TableSpan
	}
	return nil
}

func (m *RegisterDispatcherRequest) GetStartTs() uint64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *RegisterDispatcherRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *RegisterDispatcherRequest) GetActionType() ActionType {
	if m != nil {
		return m.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (m *RegisterDispatcherRequest) GetFilterConfig() *FilterConfig {
	if m != nil {
		return m.FilterConfig
	}
	return nil
}

func (m *RegisterDispatcherRequest) GetEnableSyncPoint() bool {
	if m != nil {
		return m.EnableSyncPoint
	}
	return false
}

func (m *RegisterDispatcherRequest) GetSyncPointTs() uint64 {
	if m != nil {
		return m.SyncPointTs
	}
	return 0
}

func (m *RegisterDispatcherRequest) GetSyncPointInterval() uint64 {
	if m != nil {
		return m.SyncPointInterval
	}
	return 0
}

func (m *RegisterDispatcherRequest) GetOnlyReuse() bool {
	if m != nil {
		return m.OnlyReuse
	}
	return false
}

func init() {
	proto.RegisterEnum("eventpb.OpType", OpType_name, OpType_value)
	proto.RegisterEnum("eventpb.ActionType", ActionType_name, ActionType_value)
	proto.RegisterType((*EventFilterRule)(nil), "eventpb.EventFilterRule")
	proto.RegisterType((*FilterConfig)(nil), "eventpb.FilterConfig")
	proto.RegisterType((*ResolvedTs)(nil), "eventpb.ResolvedTs")
	proto.RegisterType((*Event)(nil), "eventpb.Event")
	proto.RegisterType((*TxnEvent)(nil), "eventpb.TxnEvent")
	proto.RegisterType((*TableInfo)(nil), "eventpb.TableInfo")
	proto.RegisterType((*EventFeed)(nil), "eventpb.EventFeed")
	proto.RegisterType((*RegisterDispatcherRequest)(nil), "eventpb.RegisterDispatcherRequest")
}

func init() { proto.RegisterFile("eventpb/event.proto", fileDescriptor_d7fb2554dfcf7f7d) }

var fileDescriptor_d7fb2554dfcf7f7d = []byte{
	// 935 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0xae, 0x93, 0x34, 0x8d, 0x9f, 0xd3, 0x5d, 0x77, 0xba, 0x5d, 0xdc, 0x2d, 0x84, 0x92, 0x03,
	0x0a, 0x95, 0x48, 0x21, 0x80, 0x90, 0x56, 0x68, 0xa5, 0xd2, 0x7a, 0x91, 0x0f, 0xdb, 0x56, 0x13,
	0x77, 0x25, 0xb8, 0x58, 0x8e, 0xfd, 0x92, 0x1a, 0xdc, 0xb1, 0xeb, 0x99, 0x64, 0x93, 0x7f, 0x01,
	0x67, 0x4e, 0xfc, 0x1b, 0x8e, 0x7b, 0xe4, 0x06, 0x6a, 0x0f, 0xfc, 0x0d, 0xe4, 0x19, 0xc7, 0x71,
	0xb6, 0x08, 0x89, 0x53, 0x66, 0xde, 0xf7, 0xbd, 0x99, 0xf7, 0x7d, 0x6f, 0x9e, 0x03, 0xbb, 0x38,
	0x43, 0x26, 0xd2, 0xd1, 0xb1, 0xfc, 0xed, 0xa7, 0x59, 0x22, 0x12, 0xb2, 0x55, 0x04, 0x9f, 0x1d,
	0x5c, 0xa3, 0x9f, 0x89, 0x11, 0xfa, 0x39, 0xa3, 0x5c, 0x2b, 0x56, 0xf7, 0xcf, 0x1a, 0x3c, 0xb6,
	0x73, 0xe2, 0xcb, 0x28, 0x16, 0x98, 0xd1, 0x69, 0x8c, 0xc4, 0x82, 0xad, 0x1b, 0x5f, 0x04, 0xd7,
	0x98, 0x59, 0xda, 0x61, 0xbd, 0xa7, 0xd3, 0xe5, 0x96, 0x7c, 0x04, 0xed, 0x68, 0xc2, 0x92, 0x0c,
	0x3d, 0x79, 0xb8, 0x55, 0x93, 0xb0, 0xa1, 0x62, 0xf2, 0x18, 0xf2, 0x01, 0x40, 0x41, 0xe1, 0xb7,
	0xb1, 0x55, 0x97, 0x04, 0x5d, 0x45, 0x86, 0xb7, 0x31, 0xf9, 0x1a, 0xac, 0x02, 0x8e, 0x18, 0xc7,
	0x4c, 0x78, 0x33, 0x3f, 0x9e, 0xa2, 0x87, 0xf3, 0x34, 0xb3, 0x1a, 0x87, 0x5a, 0x4f, 0xa7, 0x7b,
	0x0a, 0x77, 0x24, 0xfc, 0x3a, 0x47, 0xed, 0x79, 0x9a, 0x91, 0x17, 0xf0, 0x7e, 0x91, 0x38, 0x4d,
	0x43, 0x5f, 0xa0, 0xc7, 0xf0, 0x4d, 0x35, 0x79, 0x53, 0x26, 0x17, 0x87, 0x5f, 0x49, 0xca, 0x39,
	0xbe, 0xf9, 0x8f, 0xfc, 0x24, 0x0e, 0xab, 0xf9, 0xcd, 0x87, 0xf9, 0x17, 0x71, 0xb8, 0xca, 0x5f,
	0x15, 0x1e, 0x62, 0x8c, 0x02, 0xab, 0xb9, 0x5b, 0xd5, 0xc2, 0xcf, 0x24, 0x5c, 0x26, 0x76, 0x7f,
	0xd1, 0xa0, 0xad, 0xcc, 0x3d, 0x4d, 0xd8, 0x38, 0x9a, 0x90, 0x27, 0xb0, 0x99, 0x4d, 0x63, 0xe4,
	0x85, 0xb9, 0x6a, 0x43, 0x3e, 0x85, 0xdd, 0xe2, 0x7c, 0x31, 0x67, 0x1e, 0x17, 0x7e, 0x26, 0x3c,
	0xc1, 0xa5, 0xc3, 0x0d, 0x6a, 0x2a, 0xc8, 0x9d, 0xb3, 0x61, 0x0e, 0xb8, 0x9c, 0x7c, 0x03, 0xed,
	0x4a, 0xdb, 0xb8, 0x34, 0xda, 0x18, 0x58, 0xfd, 0xa2, 0xe9, 0xfd, 0x77, 0x7a, 0x4a, 0xd7, 0xd8,
	0xdd, 0x36, 0x00, 0x45, 0x9e, 0xc4, 0x33, 0x0c, 0x5d, 0xde, 0x9d, 0xc2, 0xa6, 0xea, 0x9d, 0x09,
	0xf5, 0x9f, 0x70, 0x61, 0x69, 0x87, 0x5a, 0xaf, 0x4d, 0xf3, 0x65, 0x5e, 0xab, 0xd4, 0x69, 0xd5,
	0x64, 0x4c, 0x6d, 0xc8, 0x33, 0x68, 0x2d, 0xbd, 0xb1, 0xea, 0x12, 0x28, 0xf7, 0xa4, 0x07, 0x5b,
	0x49, 0xea, 0x89, 0x45, 0x8a, 0xb2, 0x9f, 0x8f, 0x06, 0x8f, 0xcb, 0x9a, 0x2e, 0x52, 0x77, 0x91,
	0x22, 0x6d, 0x26, 0xf2, 0xb7, 0xfb, 0x23, 0xb4, 0xdc, 0x39, 0x53, 0x37, 0x7f, 0x0c, 0x4d, 0xc9,
	0x52, 0xa6, 0x18, 0x83, 0x47, 0xeb, 0x42, 0x68, 0x81, 0x92, 0x03, 0xd0, 0x83, 0xe4, 0xe6, 0x26,
	0x2a, 0xbc, 0xd1, 0x7a, 0x0d, 0xda, 0x52, 0x01, 0x97, 0x93, 0x7d, 0x68, 0x95, 0xbe, 0xd5, 0x25,
	0xb6, 0xc5, 0x95, 0x5d, 0x5d, 0x03, 0x74, 0xd7, 0x1f, 0xc5, 0xe8, 0xb0, 0x71, 0xd2, 0xfd, 0x5b,
	0x03, 0x5d, 0xd9, 0x81, 0x18, 0x92, 0xcf, 0x00, 0x72, 0xc7, 0xd7, 0xae, 0xdf, 0x29, 0xaf, 0x5f,
	0x56, 0x48, 0x75, 0x51, 0xac, 0x38, 0xf9, 0x10, 0x8c, 0xac, 0x70, 0x6f, 0x55, 0x06, 0x64, 0xa5,
	0xa1, 0xe4, 0x05, 0x6c, 0x87, 0x11, 0x4f, 0xd5, 0xd0, 0x78, 0x51, 0x28, 0xab, 0x31, 0x06, 0xfb,
	0xfd, 0xca, 0x24, 0xf6, 0xcf, 0x4a, 0x86, 0x73, 0x46, 0xdb, 0x2b, 0xbe, 0x13, 0xca, 0x17, 0xe2,
	0x8b, 0x28, 0x91, 0x0e, 0xd6, 0xa8, 0xda, 0x90, 0xcf, 0x01, 0x44, 0xae, 0xc1, 0x8b, 0xd8, 0x38,
	0x91, 0xef, 0xdd, 0x18, 0x90, 0x55, 0xa1, 0x4b, 0x79, 0x54, 0x17, 0xa5, 0xd2, 0x5f, 0x1b, 0xb0,
	0x4f, 0x71, 0x12, 0x71, 0x81, 0xd9, 0xea, 0x3e, 0x8a, 0xb7, 0x53, 0xe4, 0x22, 0x2f, 0x33, 0xb8,
	0xf6, 0xd9, 0x04, 0xc7, 0x88, 0x61, 0x5e, 0xa6, 0xf6, 0x2f, 0x65, 0x9e, 0x96, 0x8c, 0xbc, 0xcc,
	0x15, 0xdf, 0x09, 0x1f, 0xca, 0xac, 0xfd, 0x3f, 0x99, 0x5f, 0x2d, 0x05, 0xf1, 0xd4, 0x67, 0x85,
	0x47, 0x4f, 0xd7, 0x92, 0xa5, 0xa8, 0x61, 0xea, 0xb3, 0x42, 0x54, 0xbe, 0x5c, 0x6b, 0x73, 0x63,
	0xad, 0xcd, 0xf9, 0xf3, 0xe0, 0x98, 0xcd, 0x54, 0x35, 0xea, 0x8b, 0xd0, 0x52, 0x01, 0x27, 0x24,
	0x5f, 0x82, 0xe1, 0x07, 0x22, 0x4a, 0x98, 0x7a, 0x9d, 0x4d, 0xf9, 0x3a, 0x77, 0x4b, 0x03, 0x4f,
	0x24, 0x26, 0x5f, 0x28, 0xf8, 0xe5, 0x9a, 0x3c, 0x87, 0xed, 0xb1, 0x9c, 0x1a, 0x2f, 0x90, 0xe3,
	0x2b, 0x87, 0xdd, 0x18, 0xec, 0x95, 0x79, 0xd5, 0xd9, 0xa6, 0xed, 0x71, 0x75, 0xd2, 0x8f, 0x60,
	0x07, 0x99, 0x52, 0xb8, 0x60, 0x81, 0x97, 0x26, 0x11, 0x13, 0x56, 0xeb, 0x50, 0xeb, 0xb5, 0xe8,
	0x63, 0x05, 0x0c, 0x17, 0x2c, 0xb8, 0xcc, 0xc3, 0xa4, 0x0b, 0xdb, 0x2b, 0x52, 0x2e, 0x4d, 0x97,
	0xd2, 0x0c, 0xbe, 0x64, 0xb8, 0x9c, 0xf4, 0x61, 0xb7, 0xc2, 0x89, 0x98, 0xc0, 0x6c, 0xe6, 0xc7,
	0x16, 0x48, 0xe6, 0x4e, 0xc9, 0x74, 0x0a, 0x20, 0xff, 0x16, 0x27, 0x2c, 0x5e, 0x78, 0x19, 0x4e,
	0x39, 0x5a, 0x86, 0xbc, 0x58, 0xcf, 0x23, 0x34, 0x0f, 0x1c, 0x7d, 0x02, 0x4d, 0x35, 0x92, 0x64,
	0x1b, 0x74, 0xb5, 0xba, 0x9c, 0x0a, 0x73, 0x83, 0x98, 0xd0, 0x56, 0x5b, 0xf5, 0x2d, 0x33, 0xb5,
	0xa3, 0xdf, 0x34, 0x80, 0x95, 0x41, 0xe4, 0x00, 0xde, 0x3b, 0x39, 0x75, 0x9d, 0x8b, 0x73, 0xcf,
	0xfd, 0xfe, 0xd2, 0xf6, 0xae, 0xce, 0x87, 0x97, 0xf6, 0xa9, 0xf3, 0xd2, 0xb1, 0xcf, 0xcc, 0x0d,
	0x62, 0xc1, 0x93, 0x2a, 0x48, 0xed, 0xef, 0x9c, 0xa1, 0x6b, 0x53, 0x53, 0x23, 0x4f, 0x81, 0xac,
	0x23, 0xaf, 0x2e, 0x5e, 0xdb, 0x66, 0x8d, 0xec, 0xc1, 0x4e, 0x35, 0x7e, 0x79, 0x72, 0x35, 0xb4,
	0xcd, 0xfa, 0x43, 0xfa, 0xf0, 0xea, 0x95, 0x6d, 0x36, 0xde, 0xa5, 0x53, 0x7b, 0x68, 0xbb, 0xe6,
	0xe6, 0xb7, 0xcf, 0x7f, 0xbf, 0xeb, 0x68, 0x6f, 0xef, 0x3a, 0xda, 0x5f, 0x77, 0x1d, 0xed, 0xe7,
	0xfb, 0xce, 0xc6, 0xdb, 0xfb, 0xce, 0xc6, 0x1f, 0xf7, 0x9d, 0x8d, 0x1f, 0x0e, 0x27, 0x91, 0xb8,
	0x9e, 0x8e, 0xfa, 0x41, 0x72, 0x73, 0x9c, 0x46, 0x6c, 0x12, 0xf8, 0xe9, 0xb1, 0x88, 0x82, 0x30,
	0x38, 0x2e, 0x9a, 0x38, 0x6a, 0xca, 0x7f, 0xc3, 0x2f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x13,
	0x90, 0xe0, 0x9d, 0x4a, 0x07, 0x00, 0x00,
}

func (m *EventFilterRule) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventFilterRule) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventFilterRule) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IgnoreDeleteValueExpr) > 0 {
		i -= len(m.IgnoreDeleteValueExpr)
		copy(dAtA[i:], m.IgnoreDeleteValueExpr)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.IgnoreDeleteValueExpr)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.IgnoreUpdateOldValueExpr) > 0 {
		i -= len(m.IgnoreUpdateOldValueExpr)
		copy(dAtA[i:], m.IgnoreUpdateOldValueExpr)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.IgnoreUpdateOldValueExpr)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.IgnoreUpdateNewValueExpr) > 0 {
		i -= len(m.IgnoreUpdateNewValueExpr)
		copy(dAtA[i:], m.IgnoreUpdateNewValueExpr)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.IgnoreUpdateNewValueExpr)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.IgnoreInsertValueExpr) > 0 {
		i -= len(m.IgnoreInsertValueExpr)
		copy(dAtA[i:], m.IgnoreInsertValueExpr)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.IgnoreInsertValueExpr)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.IgnoreSql) > 0 {
		for iNdEx := len(m.IgnoreSql) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.IgnoreSql[iNdEx])
			copy(dAtA[i:], m.IgnoreSql[iNdEx])
			i = encodeVarintEvent(dAtA, i, uint64(len(m.IgnoreSql[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.IgnoreEvent) > 0 {
		for iNdEx := len(m.IgnoreEvent) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.IgnoreEvent[iNdEx])
			copy(dAtA[i:], m.IgnoreEvent[iNdEx])
			i = encodeVarintEvent(dAtA, i, uint64(len(m.IgnoreEvent[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Matcher) > 0 {
		for iNdEx := len(m.Matcher) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Matcher[iNdEx])
			copy(dAtA[i:], m.Matcher[iNdEx])
			i = encodeVarintEvent(dAtA, i, uint64(len(m.Matcher[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *FilterConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FilterConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FilterConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EventFilters) > 0 {
		for iNdEx := len(m.EventFilters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EventFilters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.IgnoreTxnStartTs) > 0 {
		dAtA2 := make([]byte, len(m.IgnoreTxnStartTs)*10)
		var j1 int
		for _, num := range m.IgnoreTxnStartTs {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintEvent(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Rules) > 0 {
		for iNdEx := len(m.Rules) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Rules[iNdEx])
			copy(dAtA[i:], m.Rules[iNdEx])
			i = encodeVarintEvent(dAtA, i, uint64(len(m.Rules[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ResolvedTs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResolvedTs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResolvedTs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Event) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OpType != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.OpType))
		i--
		dAtA[i] = 0x20
	}
	if len(m.OldValue) > 0 {
		i -= len(m.OldValue)
		copy(dAtA[i:], m.OldValue)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.OldValue)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TxnEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxnEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxnEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StartTs != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.StartTs))
		i--
		dAtA[i] = 0x18
	}
	if m.CommitTs != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.CommitTs))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Events) > 0 {
		for iNdEx := len(m.Events) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Events[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *TableInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TableInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TableInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *EventFeed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventFeed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventFeed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TableInfo != nil {
		{
			size, err := m.TableInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Ratio != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Ratio))))
		i--
		dAtA[i] = 0x25
	}
	if m.DispatcherId != nil {
		{
			size, err := m.DispatcherId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ResolvedTs != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ResolvedTs))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TxnEvents) > 0 {
		for iNdEx := len(m.TxnEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TxnEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RegisterDispatcherRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterDispatcherRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisterDispatcherRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OnlyReuse {
		i--
		if m.OnlyReuse {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.SyncPointInterval != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.SyncPointInterval))
		i--
		dAtA[i] = 0x50
	}
	if m.SyncPointTs != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.SyncPointTs))
		i--
		dAtA[i] = 0x48
	}
	if m.EnableSyncPoint {
		i--
		if m.EnableSyncPoint {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.FilterConfig != nil {
		{
			size, err := m.FilterConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.ActionType != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ActionType))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ServerId) > 0 {
		i -= len(m.ServerId)
		copy(dAtA[i:], m.ServerId)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.ServerId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.StartTs != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.StartTs))
		i--
		dAtA[i] = 0x20
	}
	if m.TableSpan != nil {
		{
			size, err := m.TableSpan.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.DispatcherId != nil {
		{
			size, err := m.DispatcherId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.ChangefeedId != nil {
		{
			size, err := m.ChangefeedId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventFilterRule) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Matcher) > 0 {
		for _, s := range m.Matcher {
			l = len(s)
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if len(m.IgnoreEvent) > 0 {
		for _, s := range m.IgnoreEvent {
			l = len(s)
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if len(m.IgnoreSql) > 0 {
		for _, s := range m.IgnoreSql {
			l = len(s)
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	l = len(m.IgnoreInsertValueExpr)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.IgnoreUpdateNewValueExpr)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.IgnoreUpdateOldValueExpr)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.IgnoreDeleteValueExpr)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *FilterConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Rules) > 0 {
		for _, s := range m.Rules {
			l = len(s)
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if len(m.IgnoreTxnStartTs) > 0 {
		l = 0
		for _, e := range m.IgnoreTxnStartTs {
			l += sovEvent(uint64(e))
		}
		n += 1 + sovEvent(uint64(l)) + l
	}
	if len(m.EventFilters) > 0 {
		for _, e := range m.EventFilters {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func (m *ResolvedTs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Event) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.OldValue)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.OpType != 0 {
		n += 1 + sovEvent(uint64(m.OpType))
	}
	return n
}

func (m *TxnEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Events) > 0 {
		for _, e := range m.Events {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if m.CommitTs != 0 {
		n += 1 + sovEvent(uint64(m.CommitTs))
	}
	if m.StartTs != 0 {
		n += 1 + sovEvent(uint64(m.StartTs))
	}
	return n
}

func (m *TableInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *EventFeed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TxnEvents) > 0 {
		for _, e := range m.TxnEvents {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if m.ResolvedTs != 0 {
		n += 1 + sovEvent(uint64(m.ResolvedTs))
	}
	if m.DispatcherId != nil {
		l = m.DispatcherId.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Ratio != 0 {
		n += 5
	}
	if m.TableInfo != nil {
		l = m.TableInfo.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *RegisterDispatcherRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChangefeedId != nil {
		l = m.ChangefeedId.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.DispatcherId != nil {
		l = m.DispatcherId.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.TableSpan != nil {
		l = m.TableSpan.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.StartTs != 0 {
		n += 1 + sovEvent(uint64(m.StartTs))
	}
	l = len(m.ServerId)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.ActionType != 0 {
		n += 1 + sovEvent(uint64(m.ActionType))
	}
	if m.FilterConfig != nil {
		l = m.FilterConfig.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.EnableSyncPoint {
		n += 2
	}
	if m.SyncPointTs != 0 {
		n += 1 + sovEvent(uint64(m.SyncPointTs))
	}
	if m.SyncPointInterval != 0 {
		n += 1 + sovEvent(uint64(m.SyncPointInterval))
	}
	if m.OnlyReuse {
		n += 2
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventFilterRule) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventFilterRule: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventFilterRule: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Matcher", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Matcher = append(m.Matcher, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreEvent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IgnoreEvent = append(m.IgnoreEvent, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreSql", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IgnoreSql = append(m.IgnoreSql, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreInsertValueExpr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IgnoreInsertValueExpr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreUpdateNewValueExpr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IgnoreUpdateNewValueExpr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreUpdateOldValueExpr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IgnoreUpdateOldValueExpr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreDeleteValueExpr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IgnoreDeleteValueExpr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FilterConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FilterConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FilterConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rules", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rules = append(m.Rules, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.IgnoreTxnStartTs = append(m.IgnoreTxnStartTs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowEvent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthEvent
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthEvent
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.IgnoreTxnStartTs) == 0 {
					m.IgnoreTxnStartTs = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowEvent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.IgnoreTxnStartTs = append(m.IgnoreTxnStartTs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreTxnStartTs", wireType)
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventFilters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EventFilters = append(m.EventFilters, &EventFilterRule{})
			if err := m.EventFilters[len(m.EventFilters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResolvedTs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResolvedTs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResolvedTs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Event) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldValue", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OldValue = append(m.OldValue[:0], dAtA[iNdEx:postIndex]...)
			if m.OldValue == nil {
				m.OldValue = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpType", wireType)
			}
			m.OpType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpType |= OpType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TxnEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxnEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxnEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Events", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Events = append(m.Events, &Event{})
			if err := m.Events[len(m.Events)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitTs", wireType)
			}
			m.CommitTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitTs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTs", wireType)
			}
			m.StartTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TableInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TableInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TableInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventFeed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventFeed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventFeed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxnEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxnEvents = append(m.TxnEvents, &TxnEvent{})
			if err := m.TxnEvents[len(m.TxnEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolvedTs", wireType)
			}
			m.ResolvedTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolvedTs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DispatcherId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DispatcherId == nil {
				m.DispatcherId = &heartbeatpb.DispatcherID{}
			}
			if err := m.DispatcherId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ratio", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Ratio = float32(math.Float32frombits(v))
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TableInfo == nil {
				m.TableInfo = &TableInfo{}
			}
			if err := m.TableInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterDispatcherRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterDispatcherRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterDispatcherRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChangefeedId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ChangefeedId == nil {
				m.ChangefeedId = &heartbeatpb.ChangefeedID{}
			}
			if err := m.ChangefeedId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DispatcherId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DispatcherId == nil {
				m.DispatcherId = &heartbeatpb.DispatcherID{}
			}
			if err := m.DispatcherId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableSpan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TableSpan == nil {
				m.TableSpan = &heartbeatpb.TableSpan{}
			}
			if err := m.TableSpan.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTs", wireType)
			}
			m.StartTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionType", wireType)
			}
			m.ActionType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionType |= ActionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilterConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FilterConfig == nil {
				m.FilterConfig = &FilterConfig{}
			}
			if err := m.FilterConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableSyncPoint", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableSyncPoint = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SyncPointTs", wireType)
			}
			m.SyncPointTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SyncPointTs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SyncPointInterval", wireType)
			}
			m.SyncPointInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SyncPointInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnlyReuse", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OnlyReuse = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
